### ISSUE TITLE
Virtual Scrolling

### ISSUE THREAD

**Issue by manjusaharan** [surgeforward/Surge-SlickGrid-Extensions#5] opened 2013-08-05 06:55 UTC
Hi,
One of our client have requirement of loading data around 267 columns and having around 300000-40000 rows. I tried to dot he same by using JSON Datasource. But the size of JSON file is around 167 MB. And while loading the same data , it is always giving SystemOutOfMemory exception. I am not sure how can I implement virtual scrolling effectively. Please help me to do the same. Every thing in our grid will be dynamic as structure of the file cahnges frequently.
Thanks,
Manju

**Comment by togakangaroo** [comment] 2013-08-05 15:19
I'm not sure what the issue is. Are you using paging? [If you look at the demo](http://platformdemo.surgeforward.com/Grid/LargeData) you can see that the GET queries are getting `from` and `to` parameters in the url. You have to handle these on the server. I see no reason why your returned dataset should be 167MB unless you're returning everything

A bit of math...assuming an ascii character set with an average of 10 characters per cell. That's 261KB just to hold the text of 100 rows. Double that for each of the json column names and you still get only 512KB. \* And - depending on what exactly you're doing, your page size should be a lot smaller than 100 rows, in the linked example it's just 4.

I DO have to ask why on earth you're rendering a grid with 267 columns though? This is not a user interface that is useful to anybody. Humans cannot work with that much data at once. This is almost always an indicator that someone is doing a bad job with business analysis. 

On the other hand, although the data is not a huge amount of memory, scrolling through this table will cause a lot of Http and database traffic which will slow down your network AND the server. In the browser in the meantime, even modern chrome with v8 and crankshaft will have some issues rendering such a large table; that is a lot of css reflow calculations.

You have to realize that a web ui with this much data presented at once is not a common thing to do and not something that is supported by any tool that I know. For a good experience _you are going to have to change the tool or change the spec._ To change the slickGrid tool will possibly take weeks or even months - since you will want to add virtual rendering in two dimensions - and require a fairly expert knowledge of javascript (you should be able to read and understand the jQuery source code with no problem).

A much easier approach is to go back to your designer/client/BA and explain to them that this user interface is very non-standard and will take several months to code. Try to guide them down a path of something that would be more useful for their situation. For example, maybe they have several different user roles: role 1 only uses columns A,C,D,E; role 2 only uses E, X, Y, and role 3 only uses C,D,Y,Z. You can code that as three different pages with three different grids. It is always a good idea if you can figure out a way to present the ui with no grid at all.

`*` The amount of json data transferred can be further cut down by pivoting your json data on the server, and then pivoting back on the client. For example if your data is

```
[{name: "Bob", age: 29, occupation: "Sales"}, {name: "Jenny", age: 44, occupation: "DBA"}, ... ]
```

you will save a lot of bytes by pivoting it to

```
{
    name: ["Bob", "Jenny", ... ],
    age: [29, 44, ... },
    occupation: ["Sales", "DBA", ... ]
}
```

**Closed as completed by togakangaroo** 2013-08-05 15:19 UTC

**Comment by manjusaharan** [comment] 2013-08-06 09:29
Actually main requirement of our client is to create web application simmilar to EXCEL. it is strict requirement from our client that they dont want paging and need to load complete data as a whole and the scenario that I mentioned above 40000 records having 200 columns is for the Administrator who can have full access to that data. 
I tried pivoting and it reduces the file size to 60 MB from 167 MB but as I am a newbie to jquery and json so not very much familiar about unpivoting. Can you please help me in locating some good resource from where I find some base samples for unpivoting the same sample shown by you above..
Thanks,
Manju

**Comment by togakangaroo** [comment] 2013-08-06 14:32
SlickGrid does not do visible paging, instead it does bottomless scrolling where the data pages are loaded as you scroll. If you look at the link I posted all 2 million records are not loaded at one time, they are loaded piece by piece as the user moves through the grid. You implement paging on the server, not on the client.

[Here is an example of unpivoting](http://jsbin.com/oliyam/1/edit) I used the lodash library for this - you can probably get a small speed boost by doing iterations natively.

---

This might work but keep in mind that this will be incredibly slow - it might even crash the browser. I'm willing to bet that older versions of IE will not be able to handle this. That is a lot of data to hold in memory and move through very quickly (in addition to the initial download which can take a long time).

The issue is that the web is not a good place to try and replicate Excel - web applications work very differently from desktop applications. Very few applications can do it - Google Docs can do some of the things that Excel does and it has tens of thousands of hours behind it from the smartest engineers in the world.

You might have to get clever - can you just use Google Docs? You could store the data in there (don't use a database or mirror the database into gdocs), embed it in an iframe on the page, and your application can interact with the API.

Maybe you can just generate an excel document for administrators so that they can download it?

Maybe you can write some excel scripts so that they can use excel to connect directly to your database?

---

Beyond I still think that even for an administrator this Ui is useless. How will they ever find anything on a spreadsheet that big? Do you intend to have client-side filtering? Are you going to filter through 120MB of JSON in the browser every single time they do a search?

I really recommend you fight back on the exact requirements as they sound nearly impossible to me. Fortunately the business case is never "I want to see a big spreadsheet in excel". It is usually something along the lines of "I want to see recent changes in the system so I can check that nothing went wrong yesterday" and there are always easier ways of doing this than a big grid.
